=== mmmahhhhe/K-Meter/skins/include/dtd/kmeter-skin.dtd
<!ENTITY % main_components
          "button_k20,
           button_k14,
           button_k12,
           button_normal,
           button_itu,
           button_rms,
           button_hold,
           button_peaks,
           button_expand,
           button_discrete,
           button_skin,
           button_mono,
           button_dim,
           button_mute,
           button_reset,
           button_validate,
           button_about,
           label_debug
">

<!ENTITY % stereo_components
          "meter_phase_correlation,
           meter_stereo
">

<!ENTITY % main_components_optional
          "button_k20?,
           button_k14?,
           button_k12?,
           button_normal?,
           button_itu?,
           button_rms?,
           button_hold?,
           button_peaks?,
           button_expand?,
           button_discrete?,
           button_skin?,
           button_mono?,
           button_dim?,
           button_mute?,
           button_reset?,
           button_validate?,
           button_about?,
           label_debug?
">

<!ENTITY % stereo_components_optional
          "meter_phase_correlation?,
           meter_stereo?
">

<!ENTITY % kmeter_background
          "background,
           meter_graduation*
">

<!ENTITY % kmeter_components_itu
          "meter_kmeter
">

<!ENTITY % kmeter_components_rms_stereo
          "meter_kmeter_left,
           meter_kmeter_right
">

<!ENTITY % kmeter_components_rms_surround
          "%kmeter_components_rms_stereo;,
           meter_kmeter_center,
           meter_kmeter_lfe,
           meter_kmeter_ls,
           meter_kmeter_rs
">

<!ENTITY % itu_components
          "label_over,
           label_peak,
           label_true_peak
">

<!ENTITY % rms_components_stereo
          "label_over_left,
           label_over_right,
           label_peak_left,
           label_peak_right,
           label_true_peak_left,
           label_true_peak_right
">

<!ENTITY % rms_components_surround
          "label_over_left,
           label_over_right,
           label_over_center,
           label_over_lfe,
           label_over_ls,
           label_over_rs,
           label_peak_left,
           label_peak_right,
           label_peak_center,
           label_peak_lfe,
           label_peak_ls,
           label_peak_rs,
           label_true_peak_left,
           label_true_peak_right,
           label_true_peak_center,
           label_true_peak_lfe,
           label_true_peak_ls,
           label_true_peak_rs
">

<!ENTITY % itu_components_optional
          "label_over?,
           label_peak?,
           label_true_peak?
">

<!ENTITY % rms_components_stereo_optional
          "label_over_left?,
           label_over_right?,
           label_peak_left?,
           label_peak_right?,
           label_true_peak_left?,
           label_true_peak_right?
">

<!ENTITY % rms_components_surround_optional
          "label_over_left?,
           label_over_right?,
           label_over_center?,
           label_over_lfe?,
           label_over_ls?,
           label_over_rs?,
           label_peak_left?,
           label_peak_right?,
           label_peak_center?,
           label_peak_lfe?,
           label_peak_ls?,
           label_peak_rs?,
           label_true_peak_left?,
           label_true_peak_right?,
           label_true_peak_center?,
           label_true_peak_lfe?,
           label_true_peak_ls?,
           label_true_peak_rs?
">

<!ENTITY % attrs_colour_hsba
          "hue CDATA #REQUIRED
           saturation CDATA #REQUIRED
           brightness CDATA #REQUIRED
">

<!ENTITY % attrs_image_position
          "x CDATA #REQUIRED
           y CDATA #REQUIRED
">

<!ENTITY % attrs_image_spacing
          "spacing_left CDATA #IMPLIED
           spacing_top CDATA #IMPLIED
">

<!ENTITY % attrs_font
          "font_size CDATA #IMPLIED
">

<!ENTITY % attrs_background
          "image_no_peaks CDATA #REQUIRED
           image_peaks CDATA #REQUIRED
           image_expanded_no_peaks CDATA #REQUIRED
           image_expanded_peaks CDATA #REQUIRED
">

<!ENTITY % attrs_meter_graduation
          "%attrs_image_position;
           image_no_peaks CDATA #REQUIRED
           image_peaks CDATA #REQUIRED
           image_expanded_no_peaks CDATA #REQUIRED
           image_expanded_peaks CDATA #REQUIRED
">

<!ENTITY % attrs_button
          "%attrs_image_position;
           image_on CDATA #REQUIRED
           image_over CDATA #IMPLIED
           image_off CDATA #REQUIRED
">

<!ENTITY % attrs_label
          "%attrs_image_position;
           image CDATA #REQUIRED
">

<!ENTITY % attrs_state_label
          "%attrs_image_position;
           %attrs_image_spacing;
           %attrs_font;
           colour_on CDATA #IMPLIED
           colour_off CDATA #IMPLIED
           image_on CDATA #REQUIRED
           image_off CDATA #REQUIRED
">

<!ENTITY % attrs_meter
          "%attrs_image_position;
           segment_width CDATA #REQUIRED
           vertical (true | false) #REQUIRED
           image CDATA #REQUIRED
           image_expanded CDATA #REQUIRED
">

<!ENTITY % attrs_meter_with_needle
          "%attrs_image_position;
           %attrs_image_spacing;
           image CDATA #REQUIRED
           image_needle CDATA #REQUIRED
">


<!ELEMENT kmeter-skin (settings,
                       default,
                       stereo_itu?, stereo_itu_k20, stereo_itu_k14, stereo_itu_k12, stereo_itu_normal,
                       stereo_rms?, stereo_rms_k20, stereo_rms_k14, stereo_rms_k12, stereo_rms_normal,
                       surround_itu?, surround_itu_k20, surround_itu_k14, surround_itu_k12, surround_itu_normal,
                       surround_rms?, surround_rms_k20, surround_rms_k14, surround_rms_k12, surround_rms_normal)>
    <!ATTLIST kmeter-skin
              name CDATA #REQUIRED
              orientation (vertical | horizontal) #REQUIRED
              path CDATA #REQUIRED
              version CDATA "1.3"
    >

    <!ELEMENT settings (kmeter_segment, kmeter_colour_red, kmeter_colour_amber, kmeter_colour_green,
                        kmeter_colour_nonlinear)>

         <!ELEMENT kmeter_segment (#PCDATA)>
            <!ATTLIST kmeter_segment height CDATA #REQUIRED>

         <!ELEMENT kmeter_colour_red (#PCDATA)>
             <!ATTLIST kmeter_colour_red %attrs_colour_hsba;>

         <!ELEMENT kmeter_colour_amber (#PCDATA)>
            <!ATTLIST kmeter_colour_amber %attrs_colour_hsba;>

         <!ELEMENT kmeter_colour_green (#PCDATA)>
            <!ATTLIST kmeter_colour_green %attrs_colour_hsba;>

         <!ELEMENT kmeter_colour_nonlinear (#PCDATA)>
            <!ATTLIST kmeter_colour_nonlinear %attrs_colour_hsba;>

    <!ELEMENT default (%main_components;)>

    <!ELEMENT stereo_itu (%main_components_optional;, %stereo_components;, %itu_components;)>
    <!ELEMENT stereo_rms (%main_components_optional;, %stereo_components;, %rms_components_stereo;)>
    <!ELEMENT surround_itu (%main_components_optional;, %itu_components;)>
    <!ELEMENT surround_rms (%main_components_optional;, %rms_components_surround;)>

    <!ELEMENT stereo_itu_k20 (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %stereo_components_optional;, %itu_components_optional;)>
    <!ELEMENT stereo_itu_k14 (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %stereo_components_optional;, %itu_components_optional;)>
    <!ELEMENT stereo_itu_k12 (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %stereo_components_optional;, %itu_components_optional;)>
    <!ELEMENT stereo_itu_normal (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %stereo_components_optional;, %itu_components_optional;)>

    <!ELEMENT stereo_rms_k20 (%kmeter_background;, %kmeter_components_rms_stereo;, %main_components_optional;, %stereo_components_optional;, %rms_components_stereo_optional;)>
    <!ELEMENT stereo_rms_k14 (%kmeter_background;, %kmeter_components_rms_stereo;, %main_components_optional;, %stereo_components_optional;, %rms_components_stereo_optional;)>
    <!ELEMENT stereo_rms_k12 (%kmeter_background;, %kmeter_components_rms_stereo;, %main_components_optional;, %stereo_components_optional;, %rms_components_stereo_optional;)>
    <!ELEMENT stereo_rms_normal (%kmeter_background;, %kmeter_components_rms_stereo;, %main_components_optional;, %stereo_components_optional;, %rms_components_stereo_optional;)>

    <!ELEMENT surround_itu_k20 (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %itu_components_optional;)>
    <!ELEMENT surround_itu_k14 (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %itu_components_optional;)>
    <!ELEMENT surround_itu_k12 (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %itu_components_optional;)>
    <!ELEMENT surround_itu_normal (%kmeter_background;, %kmeter_components_itu;, %main_components_optional;, %itu_components_optional;)>

    <!ELEMENT surround_rms_k20 (%kmeter_background;, %kmeter_components_rms_surround;, %main_components_optional;, %rms_components_surround_optional;)>
    <!ELEMENT surround_rms_k14 (%kmeter_background;, %kmeter_components_rms_surround;, %main_components_optional;, %rms_components_surround_optional;)>
    <!ELEMENT surround_rms_k12 (%kmeter_background;, %kmeter_components_rms_surround;, %main_components_optional;, %rms_components_surround_optional;)>
    <!ELEMENT surround_rms_normal (%kmeter_background;, %kmeter_components_rms_surround;, %main_components_optional;, %rms_components_surround_optional;)>

        <!ELEMENT background (#PCDATA)>
            <!ATTLIST background %attrs_background;>

        <!ELEMENT meter_graduation (#PCDATA)>
            <!ATTLIST meter_graduation %attrs_meter_graduation;>

        <!ELEMENT button_k20 (#PCDATA)>
            <!ATTLIST button_k20 %attrs_button;>

        <!ELEMENT button_k14 (#PCDATA)>
            <!ATTLIST button_k14 %attrs_button;>

        <!ELEMENT button_k12 (#PCDATA)>
            <!ATTLIST button_k12 %attrs_button;>

        <!ELEMENT button_normal (#PCDATA)>
            <!ATTLIST button_normal %attrs_button;>

        <!ELEMENT button_itu (#PCDATA)>
            <!ATTLIST button_itu %attrs_button;>

        <!ELEMENT button_rms (#PCDATA)>
            <!ATTLIST button_rms %attrs_button;>

        <!ELEMENT button_hold (#PCDATA)>
            <!ATTLIST button_hold %attrs_button;>

        <!ELEMENT button_peaks (#PCDATA)>
            <!ATTLIST button_peaks %attrs_button;>

        <!ELEMENT button_expand (#PCDATA)>
            <!ATTLIST button_expand %attrs_button;>

        <!ELEMENT button_discrete (#PCDATA)>
            <!ATTLIST button_discrete %attrs_button;>

        <!ELEMENT button_skin (#PCDATA)>
            <!ATTLIST button_skin %attrs_button;>

        <!ELEMENT button_mono (#PCDATA)>
            <!ATTLIST button_mono %attrs_button;>

        <!ELEMENT button_dim (#PCDATA)>
            <!ATTLIST button_dim %attrs_button;>

        <!ELEMENT button_mute (#PCDATA)>
            <!ATTLIST button_mute %attrs_button;>

        <!ELEMENT button_reset (#PCDATA)>
            <!ATTLIST button_reset %attrs_button;>

        <!ELEMENT button_validate (#PCDATA)>
            <!ATTLIST button_validate %attrs_button;>

        <!ELEMENT button_about (#PCDATA)>
            <!ATTLIST button_about %attrs_button;>

        <!ELEMENT label_debug (#PCDATA)>
            <!ATTLIST label_debug %attrs_label;>

        <!ELEMENT label_over (#PCDATA)>
            <!ATTLIST label_over %attrs_state_label;>

        <!ELEMENT label_over_left (#PCDATA)>
            <!ATTLIST label_over_left %attrs_state_label;>

        <!ELEMENT label_over_right (#PCDATA)>
            <!ATTLIST label_over_right %attrs_state_label;>

        <!ELEMENT label_over_center (#PCDATA)>
            <!ATTLIST label_over_center %attrs_state_label;>

        <!ELEMENT label_over_lfe (#PCDATA)>
            <!ATTLIST label_over_lfe %attrs_state_label;>

        <!ELEMENT label_over_ls (#PCDATA)>
            <!ATTLIST label_over_ls %attrs_state_label;>

        <!ELEMENT label_over_rs (#PCDATA)>
            <!ATTLIST label_over_rs %attrs_state_label;>

        <!ELEMENT label_peak (#PCDATA)>
            <!ATTLIST label_peak %attrs_state_label;>

        <!ELEMENT label_peak_left (#PCDATA)>
            <!ATTLIST label_peak_left %attrs_state_label;>

        <!ELEMENT label_peak_right (#PCDATA)>
            <!ATTLIST label_peak_right %attrs_state_label;>

        <!ELEMENT label_peak_center (#PCDATA)>
            <!ATTLIST label_peak_center %attrs_state_label;>

        <!ELEMENT label_peak_lfe (#PCDATA)>
            <!ATTLIST label_peak_lfe %attrs_state_label;>

        <!ELEMENT label_peak_ls (#PCDATA)>
            <!ATTLIST label_peak_ls %attrs_state_label;>

        <!ELEMENT label_peak_rs (#PCDATA)>
            <!ATTLIST label_peak_rs %attrs_state_label;>

        <!ELEMENT label_true_peak (#PCDATA)>
            <!ATTLIST label_true_peak %attrs_state_label;>

        <!ELEMENT label_true_peak_left (#PCDATA)>
            <!ATTLIST label_true_peak_left %attrs_state_label;>

        <!ELEMENT label_true_peak_right (#PCDATA)>
            <!ATTLIST label_true_peak_right %attrs_state_label;>

        <!ELEMENT label_true_peak_center (#PCDATA)>
            <!ATTLIST label_true_peak_center %attrs_state_label;>

        <!ELEMENT label_true_peak_lfe (#PCDATA)>
            <!ATTLIST label_true_peak_lfe %attrs_state_label;>

        <!ELEMENT label_true_peak_ls (#PCDATA)>
            <!ATTLIST label_true_peak_ls %attrs_state_label;>

        <!ELEMENT label_true_peak_rs (#PCDATA)>
            <!ATTLIST label_true_peak_rs %attrs_state_label;>

        <!ELEMENT meter_kmeter (#PCDATA)>
            <!ATTLIST meter_kmeter %attrs_meter;>

        <!ELEMENT meter_kmeter_left (#PCDATA)>
            <!ATTLIST meter_kmeter_left %attrs_meter;>

        <!ELEMENT meter_kmeter_right (#PCDATA)>
            <!ATTLIST meter_kmeter_right %attrs_meter;>

        <!ELEMENT meter_kmeter_center (#PCDATA)>
            <!ATTLIST meter_kmeter_center %attrs_meter;>

        <!ELEMENT meter_kmeter_lfe (#PCDATA)>
            <!ATTLIST meter_kmeter_lfe %attrs_meter;>

        <!ELEMENT meter_kmeter_ls (#PCDATA)>
            <!ATTLIST meter_kmeter_ls %attrs_meter;>

        <!ELEMENT meter_kmeter_rs (#PCDATA)>
            <!ATTLIST meter_kmeter_rs %attrs_meter;>

        <!ELEMENT meter_phase_correlation (#PCDATA)>
            <!ATTLIST meter_phase_correlation %attrs_meter_with_needle;>

        <!ELEMENT meter_stereo (#PCDATA)>
            <!ATTLIST meter_stereo %attrs_meter_with_needle;>

=== mmmahhhhe/K-Meter/bin/kmeter-skins/legacy.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE kmeter-skin SYSTEM "include/dtd/kmeter-skin.dtd">
<?xml-stylesheet type="text/xsl" href="include/xslt/skin_svg.xslt"?>

<kmeter-skin
	name="Legacy"
	orientation="vertical"
	path="legacy"
	version="1.0">

	<default>
		<button_k20
			x="130"
			y="10"
			width="60"
			height="20"
			image_on="buttons/button_k20_on.png"
			image_off="buttons/button_k20_off.png"
		/>

		<button_k14
			x="130"
			y="35"
			width="60"
			height="20"
			image_on="buttons/button_k14_on.png"
			image_off="buttons/button_k14_off.png"
		/>

		<button_k12
			x="130"
			y="60"
			width="60"
			height="20"
			image_on="buttons/button_k12_on.png"
			image_off="buttons/button_k12_off.png"
		/>

		<button_normal
			x="130"
			y="85"
			width="60"
			height="20"
			image_on="buttons/button_normal_on.png"
			image_off="buttons/button_normal_off.png"
		/>

		<button_itu
			x="130"
			y="125"
			width="60"
			height="20"
			image_on="buttons/button_itu_on.png"
			image_off="buttons/button_itu_off.png"
		/>

		<button_rms
			x="130"
			y="150"
			width="60"
			height="20"
			image_on="buttons/button_rms_on.png"
			image_off="buttons/button_rms_off.png"
		/>

		<button_hold
			x="130"
			y="190"
			width="60"
			height="20"
			image_on="buttons/button_hold_on.png"
			image_off="buttons/button_hold_off.png"
		/>

		<button_peaks
			x="130"
			y="215"
			width="60"
			height="20"
			image_on="buttons/button_peaks_on.png"
			image_off="buttons/button_peaks_off.png"
		/>

		<button_expand
			x="130"
			y="240"
			width="60"
			height="20"
			image_on="buttons/button_expand_on.png"
			image_off="buttons/button_expand_off.png"
		/>

		<button_skin
			x="130"
			y="265"
			width="60"
			height="20"
			image_on="buttons/button_skin_on.png"
			image_off="buttons/button_skin_off.png"
		/>

		<button_mono
			x="130"
			y="305"
			width="60"
			height="20"
			image_on="buttons/button_mono_on.png"
			image_off="buttons/button_mono_off.png"
		/>

		<button_reset
			x="130"
			y="330"
			width="60"
			height="20"
			image_on="buttons/button_reset_on.png"
			image_off="buttons/button_reset_off.png"
		/>

		<button_validate
			x="130"
			y="592"
			width="60"
			height="20"
			image_on="buttons/button_validate_on.png"
			image_off="buttons/button_validate_off.png"
		/>

		<button_about
			x="130"
			y="617"
			width="60"
			height="20"
			image_on="buttons/button_about_on.png"
			image_off="buttons/button_about_off.png"
		/>

		<label_debug
			x="138"
			y="560"
			width="44"
			height="11"
			image="labels/label_debug.png"
		/>
	</default>

	<stereo_itu>
		<meter_phase_correlation
			x="10"
			y="624"
			width="107"
			height="13"
			spacing_left="1"
			spacing_top="1"
			image="meters/meter_phase_correlation.png"
			>
			<needle
				width="3"
				height="11"
				image="meters/meter_phase_correlation_needle.png"
			/>
		</meter_phase_correlation>

		<meter_stereo
			x="10"
			y="607"
			width="107"
			height="13"
			spacing_left="1"
			spacing_top="1"
			image="meters/meter_stereo.png"
			>
			<needle
				width="3"
				height="11"
				image="meters/meter_stereo_needle.png"
			/>
		</meter_stereo>

		<label_over
			x="47"
			y="14"
			width="32"
			height="16"
			spacing_left="3"
			spacing_top="2"
			font_size="12"
			image_on="labels/label_over_on.png"
			image_off="labels/label_over_off.png"
		/>

		<label_peak
			x="47"
			y="32"
			width="32"
			height="16"
			spacing_left="3"
			spacing_top="2"
			font_size="12"
			image_on="labels/label_peak_on.png"
			image_off="labels/label_peak_off.png"
		/>
	</stereo_itu>

	<stereo_itu_k20>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_itu_k20_no-peaks.png"
			image_peaks="backgrounds/background_stereo_itu_k20_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_itu_k20_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_itu_k20_expanded_peaks.png"
		/>

		<meter_kmeter
			x="51"
			y="58"
			width="24"
			height="537"
			image="meters/meter_kmeter_itu_k20.png"
			image_expanded="meters/meter_kmeter_itu_k20_expanded.png"
		/>
	</stereo_itu_k20>

	<stereo_itu_k14>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_itu_k14_no-peaks.png"
			image_peaks="backgrounds/background_stereo_itu_k14_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_itu_k14_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_itu_k14_expanded_peaks.png"
		/>

		<meter_kmeter
			x="51"
			y="58"
			width="24"
			height="537"
			image="meters/meter_kmeter_itu_k14.png"
			image_expanded="meters/meter_kmeter_itu_k14_expanded.png"
		/>
	</stereo_itu_k14>

	<stereo_itu_k12>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_itu_k12_no-peaks.png"
			image_peaks="backgrounds/background_stereo_itu_k12_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_itu_k12_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_itu_k12_expanded_peaks.png"
		/>

		<meter_kmeter
			x="51"
			y="58"
			width="24"
			height="537"
			image="meters/meter_kmeter_itu_k12.png"
			image_expanded="meters/meter_kmeter_itu_k12_expanded.png"
		/>
	</stereo_itu_k12>

	<stereo_itu_normal>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_itu_normal_no-peaks.png"
			image_peaks="backgrounds/background_stereo_itu_normal_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_itu_normal_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_itu_normal_expanded_peaks.png"
		/>

		<meter_kmeter
			x="51"
			y="58"
			width="24"
			height="537"
			image="meters/meter_kmeter_itu_normal.png"
			image_expanded="meters/meter_kmeter_itu_normal_expanded.png"
		/>
	</stereo_itu_normal>

	<stereo_rms>
		<meter_phase_correlation
			x="10"
			y="624"
			width="107"
			height="13"
			spacing_left="1"
			spacing_top="1"
			image="meters/meter_phase_correlation.png"
			>
			<needle
				width="3"
				height="11"
				image="meters/meter_phase_correlation_needle.png"
			/>
		</meter_phase_correlation>

		<meter_stereo
			x="10"
			y="607"
			width="107"
			height="13"
			spacing_left="1"
			spacing_top="1"
			image="meters/meter_stereo.png"
			>
			<needle
				width="3"
				height="11"
				image="meters/meter_stereo_needle.png"
			/>
		</meter_stereo>

		<label_over_left
			x="15"
			y="14"
			width="32"
			height="16"
			spacing_left="3"
			spacing_top="2"
			font_size="12"
			image_on="labels/label_over_on.png"
			image_off="labels/label_over_off.png"
		/>

		<label_over_right
			x="79"
			y="14"
			width="32"
			height="16"
			spacing_left="3"
			spacing_top="2"
			font_size="12"
			image_on="labels/label_over_on.png"
			image_off="labels/label_over_off.png"
		/>

		<label_peak_left
			x="15"
			y="32"
			width="32"
			height="16"
			spacing_left="3"
			spacing_top="2"
			font_size="12"
			image_on="labels/label_peak_on.png"
			image_off="labels/label_peak_off.png"
		/>

		<label_peak_right
			x="79"
			y="32"
			width="32"
			height="16"
			spacing_left="3"
			spacing_top="2"
			font_size="12"
			image_on="labels/label_peak_on.png"
			image_off="labels/label_peak_off.png"
		/>
	</stereo_rms>

	<stereo_rms_k20>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_rms_k20_no-peaks.png"
			image_peaks="backgrounds/background_stereo_rms_k20_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_rms_k20_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_rms_k20_expanded_peaks.png"
		/>

		<meter_kmeter_left
			x="19"
			y="58"
			width="20"
			height="537"
			image="meters/meter_kmeter_rms_k20.png"
			image_expanded="meters/meter_kmeter_rms_k20_expanded.png"
		/>

		<meter_kmeter_right
			x="87"
			y="58"
			width="20"
			height="537"
			image="meters/meter_kmeter_rms_k20.png"
			image_expanded="meters/meter_kmeter_rms_k20_expanded.png"
		/>
	</stereo_rms_k20>

	<stereo_rms_k14>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_rms_k14_no-peaks.png"
			image_peaks="backgrounds/background_stereo_rms_k14_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_rms_k14_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_rms_k14_expanded_peaks.png"
		/>

		<meter_kmeter_left
			x="19"
			y="58"
			width="20"
			height="537"
			image="meters/meter_kmeter_rms_k14.png"
			image_expanded="meters/meter_kmeter_rms_k14_expanded.png"
		/>

		<meter_kmeter_right
			x="87"
			y="58"
			width="20"
			height="537"
			image="meters/meter_kmeter_rms_k14.png"
			image_expanded="meters/meter_kmeter_rms_k14_expanded.png"
		/>
	</stereo_rms_k14>

	<stereo_rms_k12>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_rms_k12_no-peaks.png"
			image_peaks="backgrounds/background_stereo_rms_k12_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_rms_k12_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_rms_k12_expanded_peaks.png"
		/>

		<meter_kmeter_left
			x="19"
			y="58"
			width="20"
			height="537"
			image="meters/meter_kmeter_rms_k12.png"
			image_expanded="meters/meter_kmeter_rms_k12_expanded.png"
		/>

		<meter_kmeter_right
			x="87"
			y="58"
			width="20"
			height="537"
			image="meters/meter_kmeter_rms_k12.png"
			image_expanded="meters/meter_kmeter_rms_k12_expanded.png"
		/>
	</stereo_rms_k12>

	<stereo_rms_normal>
		<background
			width="200"
			height="648"
			image_no_peaks="backgrounds/background_stereo_rms_normal_no-peaks.png"
			image_peaks="backgrounds/background_stereo_rms_normal_peaks.png"
			image_expanded_no_peaks="backgrounds/background_stereo_rms_normal_expanded_no-peaks.png"
			image_expanded_peaks="backgrounds/background_stereo_rms_normal_expanded_peaks.png"
		/>
